version: '3'

services:
  php:
    image: vandeveon/dockeravel:php-7.3
    volumes:
      - ./:/var/www/html

  php_xdebug:
    image: vandeveon/dockeravel:php-7.3
    volumes:
      - ./:/var/www/html

  web:
    image: nginx:1.17
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./dockeravel_conf/dockeravel/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8000

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysqldata:/var/lib/mysql

  node:
    image: node:12
    user: node
    working_dir: /assets
    volumes:
      - ./:/assets
    command: npm run watch

  redis:
    image: redis:5
    volumes:
      - redisdata:/data

  adminer:
    image: adminer
    ports:
      - 8090:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  mysqldata:
  redisdata:
