version: '3'

services:
  php:
    build:
      context: .
    volumes:
      - ./:/var/www/html

  php_xdebug:
    depends_on:
      - php
    build:
      context: .
    volumes:
      - ./:/var/www/html

  web:
    image: nginx:1.17
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./dcl_conf/docker-compose-laravel/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8000

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysqldata:/var/lib/mysql

  node:
    image: node:12
    user: node
    working_dir: /assets
    volumes:
      - ./:/assets
    command: npm run watch

  redis:
    image: redis:5
    volumes:
      - redisdata:/data

volumes:
  mysqldata:
  redisdata:
